version: '3.8'

volumes:
  postgres_data:
  static_volume:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: nebesnaya/foodgram-project:latest
#    command: ['python', 'manage.py', 'migrate']
    restart: always
    volumes:
      - static_volume:/code/static
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/code/static
    ports:
      - 80:80
    depends_on:
      - web
