# Generated by Django 3.0.8 on 2020-12-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(related_name='recipe_ingredient', through='recipes.Amount', to='recipes.Ingredient'),
        ),
    ]
